version: "3"
services:
  youtube_bot:
    image: youtube_tg:latest
    container_name: youtube_tg
    command: python youtube_bot.py
    #command: python dev_loop.py
    environment:
      TELEGRAM_BOT_TOKEN: your-token-here
    volumes:
      - ./:/app
