version: "3"
services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python youtube_bot.py
    environment:
      TELEGRAM_BOT_TOKEN: your-token-here
    volumes:
      - ./cipher_replaced.py:/usr/local/lib/python3.12/site-packages/pytube/cipher.py  # patch regexp

